// <auto-generated />
using System;
using BuildAbot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildAbot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildAbot.Database.Entities.Bot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TestBot",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.BotScript", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BotId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("ScriptId");

                    b.ToTable("BotScript");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BotId = 1,
                            ScriptId = 1
                        });
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 11, 8, 42, 46, 281, DateTimeKind.Local).AddTicks(6772),
                            PostId = 1,
                            Text = "TestTopComment",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 11, 8, 42, 46, 281, DateTimeKind.Local).AddTicks(6772),
                            ParentCommentId = 1,
                            PostId = 1,
                            Text = "TestChildComment",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.FavoriteScript", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteScript");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScriptId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "TestContent",
                            CreatedAt = new DateTime(2025, 4, 11, 8, 42, 46, 281, DateTimeKind.Local).AddTicks(6772),
                            Title = "TestPost",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GuideLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Script");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeLocationId = "CodeLocation",
                            Description = "TestDescription",
                            GuideLocationId = "GuideLocation",
                            Title = "TestScript",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "testmail1",
                            Password = "Passw0rd",
                            UserName = "TesterMand"
                        },
                        new
                        {
                            Id = 2,
                            Email = "testmail2",
                            Password = "Password",
                            UserName = "Supporten"
                        });
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Bot", b =>
                {
                    b.HasOne("BuildAbot.Database.Entities.User", "User")
                        .WithMany("Bots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.BotScript", b =>
                {
                    b.HasOne("BuildAbot.Database.Entities.Bot", "Bot")
                        .WithMany("BotScripts")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildAbot.Database.Entities.Script", "Script")
                        .WithMany("BotScripts")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Comment", b =>
                {
                    b.HasOne("BuildAbot.Database.Entities.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("BuildAbot.Database.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildAbot.Database.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.FavoriteScript", b =>
                {
                    b.HasOne("BuildAbot.Database.Entities.Script", "Script")
                        .WithMany("FavoriteScripts")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildAbot.Database.Entities.User", "User")
                        .WithMany("FavoriteScripts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Script");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Post", b =>
                {
                    b.HasOne("BuildAbot.Database.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Script", b =>
                {
                    b.HasOne("BuildAbot.Database.Entities.User", "User")
                        .WithMany("Scripts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Bot", b =>
                {
                    b.Navigation("BotScripts");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Comment", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.Script", b =>
                {
                    b.Navigation("BotScripts");

                    b.Navigation("FavoriteScripts");
                });

            modelBuilder.Entity("BuildAbot.Database.Entities.User", b =>
                {
                    b.Navigation("Bots");

                    b.Navigation("Comments");

                    b.Navigation("FavoriteScripts");

                    b.Navigation("Posts");

                    b.Navigation("Scripts");
                });
#pragma warning restore 612, 618
        }
    }
}
