name: Build and Deploy ASP .NET API

on:
  push:
    branches:
      - main

jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        working-directory: Backend
        run: dotnet restore

      - name: Build ASP .NET API
        working-directory: Backend
        run: dotnet build --configuration Release

      - name: Publish ASP .NET API
        working-directory: Backend
        run: dotnet publish --configuration Release --output published

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_NAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/api/
          local-dir: Backend/published/
